"""Initial migration

Revision ID: fe80beb9b442
Revises: 
Create Date: 2025-02-16 13:39:20.401061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe80beb9b442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_table('material',
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('part_number')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_serial_number', sa.String(), nullable=True),
    sa.Column('material_part_number', sa.String(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_serial_number'], ['aircraft.serial_number'], ),
    sa.ForeignKeyConstraint(['material_part_number'], ['material.part_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('material')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
